### ISSUE TITLE
Can't change signature status from Tag Menu

### ISSUE THREAD

**Issue by malvidin** [CybercentreCanada/assemblyline-ui-frontend#109]
I cannot change the status of a signature if go to the signature from the tag menu. But changing the signature from the Manage Signatures route works.

- From Submission Details
1. Click on File that matched signature
1. Right-Click on file.rule.yara value, like `maldocs.invalid_trailer_structure` 
1. Left-Click on `Go to signature`
    `https://assemblyline4/manage/signature/yara_maldocs_invalid_trailer_structure`
1. Change state of signature
1. Save Changes
    `GET 404: https://assemblyline4/api/v4/signature/change_status/undefined/NOISY/`
    `Error: "Signature not found. (undefined)"`

- From Manage Signatures
1. Query for signature `invalid_trailer_structure`
    `https://assemblyline4/manage/signatures?rows=25&offset=0&query=invalid_trailer_structure`
1. Click on signature
1. Change state of signature
1. Save Changes
    `GET 200:  https://assemblyline4/api/v4/signature/change_status/yara_maldocs_invalid_trailer_structure/DISABLED/`
    `Success: "The state of the signature was successfully changed"`

**Comment by cccs-sgaron** [comment]
Will be fixed in PR #116
