### ISSUE TITLE
Feature request: scoring

### ISSUE THREAD

**Issue by YoavLevi** [CybercentreCanada/assemblyline-ui-frontend#255]
Hello, community.
I am an old user of AL3 in an offline environment. Lately, I've deployed a new cluster of AL4 and started testing it. One of the major drawbacks of the UI I observed is that the score is no longer present in the submission(s) pages beside each file (only when hovering over it).
It would be very helpful if the feature of showing the score next to each file would be added, even as an optional parameter in the UI management interface.
Thanks in advance.

**Comment by YoavLevi** [comment]
Can this feature be optionally available in the next versions?
In organizations scoring based on YARA rules, the cumulative score has meaning. By available I mean there would be a tick box that enables this feature on and off in the UI. It would be very helpful for me and for some other users as far as I know.
thanks.

**Comment by sSharonV** [comment]
> Can this feature be optionally available in the next versions? In organizations scoring based on YARA rules, the cumulative score has meaning. By available I mean there would be a tick box that enables this feature on and off in the UI. It would be very helpful for me and for some other users as far as I know. thanks.

I was browsing the issues to see if anyone had previously asked to add this optional feature.
I'm also an old user since AL3 and our team would really appreciate this feature ASAP.
Thanks for understanding!
