### ISSUE TITLE
Bug - Find Related Results Does Not Escape Backslashes

### ISSUE THREAD

**Issue by malvidin** [CybercentreCanada/assemblyline-ui-frontend#333]
The "Find related results" does not appropriately escape backslashes before sending the value to search. 
if `file.pe.pdb_filename = "C:\Users\Path.pdb"`, the search generated is `result.sections.tags.file.pe.pdb_filename: "C:\Users\Path.pdb"`, not `result.sections.tags.file.pe.pdb_filename: "C:\\Users\\Path.pdb"`.

https://github.com/CybercentreCanada/assemblyline-ui-frontend/blob/ed895c04cdb4ad94257e769bca674162b9a12b4e/src/components/visual/Tag.tsx#L64-L68

**Comment by cccs-sgaron** [comment]
Fixed in PR #334
