### ISSUE TITLE
License of assemblyline-ui-frontend

### ISSUE THREAD

**Issue by lhviet** [CybercentreCanada/assemblyline-ui-frontend#429]
Hi team,

I really appreciate your work on this project to adopt React and build up a better UI/UX.
However, I couldn't find the License for this one.
I believe that many communities will give a thumbs up if we can leverage your work to improve security over the world.

May I know if you have any plans to add License information in near future to this project?
If yes, then what License I should expect?

Thank you in advance.
Viet.

**Comment by cccs-sgaron** [comment]
We use MIT as the licence for Assemblyline as a whole. I'll add it to the repos that are missing it.
